name: ligand_fep_workflows
channels:
  - conda-forge
  - bioconda
  - openbiosim/label/dev
dependencies:
  - ambertools
  - cinnabar
  - mdrestraintsgenerator
  - pandas
  - snakemake
  - snakemake-executor-plugin-slurm
  - somd2
